main_app/urls.py
from .views import GrubList, GrubCreate, GrubDetail, GrubDelete, GrubUpdate, ClaimCreate, PhotoDelete
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('grubs/',GrubList.as_view(), name='index'),
    path('grubs/detail/<int:pk>/',GrubDetail.as_view(), name='grubs_detail'),
    path('grubs/create/',GrubCreate.as_view(), name='grubs_create'),
    path('grubs/update/<int:pk>/',GrubUpdate.as_view(), name='grubs_update'),
    path('grubs/delete/<int:pk>/',GrubDelete.as_view(), name='grubs_delete'),
    path('photos/delete/<int:pk>/',PhotoDelete.as_view(), name='photos_delete'),
    path('accounts/signup/', views.signup, name='signup'),
    path('claims/create/',ClaimCreate.as_view(), name='claims_create'),
    #donate path
]

upforgrubs/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls')),
    path('accounts/', include('django.contrib.auth.urls'))
]

main_app/models.py
from django.contrib.auth.models import User
from email.policy import default
from django.urls import reverse
from django.db import models


TYPE = (
    ('Fresh Produce', 'Fresh'),
    ('Pantry', 'Pantry')
)

OPTION = (
    ('Pick-up', 'Pick-Up'),
    ('Delivery', 'Delivery')
)

class Grub(models.Model):
    item =  models.CharField(
        max_length=50,
        blank = True, 
        null = True
    )
    type = models.CharField(
        max_length = 50,
        choices = TYPE,
        default= TYPE[0][0]
    )
    exp = models.DateField(
        'exp date',
         blank = True,
         null = True
    )
  
    desc =  models.TextField(
        max_length=250,
        blank = True, 
        null = True
    )
    option = models.CharField(
        max_length=10,
        choices=OPTION,
        default=OPTION[0][0]
    )
    location = models.CharField(
        max_length=200,
         blank = True, 
         null = True
    )
    user = models.ForeignKey(User,  on_delete=models.CASCADE)
    def __str__(self):
       return self.item
    #    f'Photo for grub_id: {self.user} @{self.url}'

    def get_absolute_url(self):
        return reverse('grubs_detail', kwargs={'pk': self.id})

class Photo(models.Model):
    grub = models.ForeignKey(Grub,  on_delete=models.CASCADE, blank = True, 
         null = True)
    url = models.FileField(
        blank = True, 
        null = True,
    )
class Claim(models.Model):
    grub = models.ForeignKey(Grub, on_delete=models.CASCADE, blank = True, null = True)
    user = models.ForeignKey(User, on_delete=models.CASCADE, blank = True, null = True)

main_app/views.py
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.forms import UserCreationForm
from django.views.generic import ListView, DetailView
from django.db.models.signals import post_delete
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect
from .models import Grub, Photo, Claim
from django.contrib.auth import login
from django.dispatch import receiver
from django.urls import reverse
from django.db.models import Q
import boto3
import uuid
import os

def home(request):
    claims = Claim.objects.all()
    grubs = Grub.objects.all()
    matches = []
    #* loops over the claims QuerySet
    for claim in claims:
    #*querying for grubs with a claim and pushing to matches(extend)
       matches.extend(grubs.exclude(~Q(id=claim.grub.id)))
    
    filter = []
    for grub in grubs:
        #* comparing grubs with matches and pushing non-matches to filter
        if grub not in matches:
            filter.append(grub)
            #* passing filter through the render to home for display
    return render(request, 'home.html', {'grubs': filter})

def about(request):
    return render(request, 'about.html')

def signup(request):
  error_message = ''
  if request.method == 'POST':
    form = UserCreationForm(request.POST)
    if form.is_valid():
      user = form.save()
      login(request, user)
      return redirect('index')
    else:
      error_message = 'Invalid sign up - try again'
  form = UserCreationForm()
  context = {'form': form, 'error_message': error_message}
  return render(request, 'registration/signup.html', context)

    
class GrubList(ListView):
    model = Grub
    #* using built-in django method to get some data
    def get_context_data(self, **kwargs):
        #* using super to access GrubList methods
        claim = super(GrubList, self).get_context_data(**kwargs)
        #* create key in proxy object tha hold a queryset value
        claim['claims'] = Claim.objects.filter(user=self.request.user)
        return claim    

    
class GrubDetail(LoginRequiredMixin, DetailView):
    model = Grub

    def get_context_data(self, **kwargs):
        photo = super(GrubDetail, self).get_context_data(**kwargs)
        #* create two keys in proxy object of photo and places with values of a Photo Model Queryset and place api key in .env respectively
        photo['photo'] = Photo.objects.all()
        photo['places'] = os.environ.get('PLACES_API')
        return photo

class GrubCreate(LoginRequiredMixin, CreateView):
    model = Grub
    #*list needed fields for create form
    fields = ['item','type','exp','desc', 'option', 'location'] 

    def get_context_data(self, **kwargs):
        places = super(GrubCreate, self).get_context_data(**kwargs)
        places['places'] = os.environ.get('PLACES_API')
        return places
    
    def form_valid(self, form):
        #*assign logged in user to user field in before submitting grub form instance
        form.instance.user = self.request.user
        #* save form before moving to the next step
        super().form_valid(form) 
        #*get Queryset list from client-side form
        photo_file = self.request.FILES.getlist('url', None)
        #* loop over photo file
        for img in photo_file:
            if img:
                #* making a get request to boto3 client
                s3 = boto3.client('s3')
                #* create a new file name to be stored in s3 bucket
                key = uuid.uuid4().hex[:6] + img.name[img.name.rfind('.'):]

                try:
                    #*bucket name
                    bucket = os.environ['S3_BUCKET']
                    #* uploading file using boto3.client method
                    s3.upload_fileobj(img, bucket, key)
                    #* creating photo url from remote aws bucket
                    url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}"
                    #* create a photo instance of the Photo model and assigning it to the created grub
                    Photo.objects.create(url=url, grub=form.instance)
                except Exception as e:
                    print('An error occurred uploading file to S3')
                    print(e)
                    return redirect('home')
            else: 
                print('Need to upload file')
        #* redirect to created grub model instance
        return HttpResponseRedirect(self.get_success_url())


class GrubUpdate(LoginRequiredMixin, UpdateView):
    model = Grub 
    fields = ['item','type','exp','desc', 'option', 'location']
    def get_context_data(self, **kwargs):
        places = super(GrubUpdate, self).get_context_data(**kwargs)
        places['places'] = os.environ.get('PLACES_API')
        return places
    def form_valid(self, form):
        super().form_valid(form) 
        photo_file = self.request.FILES.getlist('url', None)
        for img in photo_file:
            if img:
                s3 = boto3.client('s3')
                key = uuid.uuid4().hex[:6] + img.name[img.name.rfind('.'):]
                try:
                    bucket = os.environ['S3_BUCKET']
                    s3.upload_fileobj(img, bucket, key)
                    url = f"{os.environ['S3_BASE_URL']}{bucket}/{key}" 
                    Photo.objects.create(url=url, grub=form.instance)
                except Exception as e:
                    print('An error occurred uploading file to S3')
                    print(e)
                    return redirect('home')
            else: 
                print('Need to upload file')
        return HttpResponseRedirect(self.get_success_url())
    

class GrubDelete(LoginRequiredMixin, DeleteView):
    model = Grub
    success_url = '/grubs/'

class ClaimCreate(LoginRequiredMixin, CreateView):
    model = Claim
    success_url = '/index/'
    fields = '__all__'

    def form_valid(self, form):
        #* assign user to claim from instance
        form.instance.user = self.request.user
        #* save claim with just a user instance
        super().form_valid(form)
        #* return a singular queryset of the updating grub
        grub = Grub.objects.filter(id=self.request.GET.get('id', None))
        #* returns a queryset of a the recently create claim that has no grub instance and belongs to the logged in user
        claim = Claim.objects.filter(grub=None, user=self.request.user)
        #*update the returned claim with the return grub instance
        claim.update(grub=grub[0])
        return redirect('/grubs/')

class PhotoDelete(LoginRequiredMixin, DeleteView):
    model = Photo
    #! use the built-in class method delete 
    def delete(self, request, pk):
        s3 = boto3.client('s3', aws_access_key_id=os.environ['AWS_ACCESS_KEY_ID'], aws_secret_access_key=os.environ['AWS_SECRET_ACCESS_KEY'])
        url = self.request.GET.get("url", None)
        redirect = self.request.GET.get("id", None)
        img_id = self.request.GET.get("img", None)
        #! slice the last 10 char from s3 bucket url string
        img = url[-10:]
        #! make a query fo the photo that matches the photo instace id which comes from hidden form data in template view, passed in through the request
        photo_delete = Photo.objects.get(id=img_id)
        photo_delete.delete()
        #! use the boto3 method to delete from s3 bucket(only made possible if delete_obj action is enable and versioning it disabled in AWS)
        deleted = s3.delete_object(Bucket=os.environ['S3_BUCKET'], Key=img)
        #! use django built in signal and method (first arg) to relay the deleted action of the Photo(second arg) to AWS once completed
        @receiver(post_delete, sender=Photo)
        def delete_image_file(sender, instance, **kwargs):                          
            instance.main_image.delete(False)
        return HttpResponseRedirect(reverse('grubs_detail', kwargs={'pk':redirect}))

main_app/templates/about.html
{% extends 'base.html' %}
{% block content %}
<div id="about">
<h1 class = "grubs">ABOUT</h1>
<br>
    <h6>It is estimated that food waste comprises 30%-40% of the US food supply.</h6>
    <br>
    <h6>UP4GRUBZ aims to reduce these numbers by allowing community</h6>
    <h6>members to share any of their extra or about-to-expire</h6>
    <h6>food instead of disposing of it.</h6>
    <br>
    <img class="responsive-img" src="https://hips.hearstapps.com/hmg-prod.s3.amazonaws.com/images/earth-spin5-2-1619034499.gif?crop=0.422xw:0.846xh;0.279xw,0&resize=640:*">
    <h5>POST GRUBS - CLAIM GRUBS - HELP THE PLANET!</h5>
    <br>
    <h1 class = "grubs">Our Team</h1>
    <h6>Marlin Makori</h6>
    <a href='https://github.com/MaDTrX'target='blank'><img src="https://i.imgur.com/4n9m1ZE.png" width='50px' height='50px'></a>
    <h6>Armando Ubario</h6> 
    <a href='https://github.com/mandouba' target='blank'><img src="https://i.imgur.com/4n9m1ZE.png" width='50px' height='50px'></a>
    <h6>Vergine Manucharyan</h6>
    <a href='https://github.com/vergmanu'target='blank'><img src="https://i.imgur.com/4n9m1ZE.png" width='50px' height='50px'></a>
   
<div>  

{% endblock %}

main_app/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>UP4GRUBZ</title>
    
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}"> 
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js" defer></script>
    <style>
      @import url('https://fonts.googleapis.com/css2?family=Baloo+Paaji+2:wght@500&family=Londrina+Outline&family=Londrina+Shadow&family=Londrina+Solid&family=Roboto&display=swap');
      </style>
  </head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="responsive-img" id="grubs-logo">&nbsp;&nbsp;</a></li>
        </ul>
        
        {% if user.is_authenticated %}
        
        {% endif %}
        

        <ul class="dropdown-content show-on-small" id="dropdown1">
          <li><a href="{% url 'about' %}">ABOUT</a></li>
          {% if user.is_authenticated %}
            <li><a href="{% url 'index' %}">MY GRUBS</a></li>
            <li><a href="{% url 'grubs_create' %}">POST GRUB</a></li>
            <li><a href="{% url 'logout' %}">LOGOUT</a></li>
          {% else %}
            <li><a href="{% url 'signup' %}">SIGNUP</a></li>
            <li><a href="{% url 'login' %}">LOGIN</a></li>
          {% endif %}
        </ul>
 

      <a class='dropdown-trigger right hide-on-med-and-up' href='#' data-target='dropdown1'><i class="material-icons">menu</i></a>
        <ul class="nav-text right hide-on-small-only">
            <li ><a href="{% url 'about' %}" class="resize">ABOUT</a></li>
            {% if user.is_authenticated %}
              <li><a href="{% url 'index' %}" class="resize">MY GRUBS</a></li>
              <li><a href="{% url 'grubs_create' %}" class="resize">POST GRUB</a></li>
              <li><a href="{% url 'logout' %}" class="resize">LOGOUT</a></li>
            {% else %}
              <li><a href="{% url 'signup' %}" class="resize">SIGNUP</a></li>
              <li><a href="{% url 'login' %}" class="resize">LOGIN</a></li>
            {% endif %}
          </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    <div class="row">
      <div class="card">
        <div class="card-content">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
  </main>
  <footer class="page-footer">
    {% now "Y" as current_year %}
    <div class="footer right">All Rights Reserved, &copy; {{current_year}} UP4GRUBZ &nbsp;</div>
  <script>
    const findUserLocation =  () => {
        let approved = (position) => {
            let Userlatitude = position.coords.latitude
            let Userlongitude = position.coords.longitude

        }
        const denied = () => {
            console.log('location access deinied')
        }
        navigator.geolocation.getCurrentPosition(approved, denied)
    }
    document.addEventListener('DOMContentLoaded', findUserLocation)

    document.addEventListener('DOMContentLoaded', function() {
      const elems = document.querySelectorAll('.dropdown-trigger');
      const instances = M.Dropdown.init(elems);
      
      const selectType = document.getElementById('id_type')
      M.FormSelect.init(selectType)
      const selectUser = document.getElementById('id_user')
      M.FormSelect.init(selectUser)
      const selectOption = document.getElementById('id_option')
      M.FormSelect.init(selectOption)
    })
      document.addEventListener('DOMContentLoaded', function() {
      const elems= document.getElementById('id_exp');
      const instances = M.Datepicker.init(elems,{format: 'yyyy-mm-dd'});
    }); 
    let autocomplete
    function initAutoComplete() {
    autocomplete = new google.maps.places.Autocomplete(document.getElementById('id_location'),
      {
          types:[], 
          componentRestriction: {'country': ['US']}, 
          fields: ['place_id','geometry', 'name']
      })
    }
    window.addEventListener('DOMContentLoaded', function () {
      console.log(window.innerWidth)
      let col = document.querySelectorAll('section')
      col.forEach(section => {
        if (window.innerWidth < 550) {
         section.classList.remove('col')
        }
        })
     })
     window.addEventListener('resize', function () {
       let col = document.querySelectorAll('section')
       col.forEach(section => {
          if (window.innerWidth < 550) { 
            section.classList.remove('col')
          } else {
            section.classList.add('col')
          }
          })
       })
    document.addEventListener('DOMContentLoaded', function() {
    let tr = document.createElement('tr')
    let tbody= document.querySelector('tbody')
    let lastTr= tbody.lastElementChild

    tbody.appendChild(tr).innerHTML = '<th><label>Photos:</label></th><td><input type="file" name="url" id="id_url" multiple></td>'

    let item= document.getElementById('id_item')
    item.setAttribute('placeholder', 'Enter an item')

    let desc=document.getElementById('id_desc')
    desc.setAttribute('placeholder', 'Enter a description')
   
    document.addEventListener('resize', function (){
    })
  })
</script>
<script async
    src="https://maps.googleapis.com/maps/api/js?key={{places}}&libraries=places&callback=initAutoComplete">
</script>
</body>
</html> 

main_app/templates/home.html

{% extends 'base.html' %}
{% block content %}

<h1 class = "grubs"> GRAB SOME GRUBS </h1>

{% for grub in grubs %}
<a href="{% url 'grubs_detail' grub.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title"> {{ grub.item }} </span>
            <p>Type: {{grub.type}}</p>
            <p> Location: {{grub.location}} </p>
        </div>
    </div>
</a>
{% endfor %}
{% endblock %}